version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.1
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy psycopg2-binary
      - AIRFLOW_UID=50000
      - PG_HOST=postgres_container
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_STAGING_DB=etl_staging_db
      - PG_PROD_DB=etl_production_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data/incoming:/opt/airflow/data/incoming
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow scheduler & airflow webserver"

  metabase:
    image: metabase/metabase:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "etl_production_db"
      MB_DB_PORT: 5432
      MB_DB_USER: "postgres"
      MB_DB_PASS: "postgres"
      MB_DB_HOST: "postgres_container"
    depends_on:
      - postgres

volumes:
  postgres_data:
